version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    entrypoint: ./docker-entrypoint.sh
    restart: unless-stopped
    environment:
      APP_ENV: "PROD"
      FLASK_DEBUG: "True"
      APP_PORT: 5000
    volumes:
      - appdata:/var/www
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq
    networks:
      - frontend
      - backend
  redis:
    image: "redis:alpine"
    restart: unless-stopped
    container_name: redis
    hostname: redis
    networks:
      - backend
    volumes:
      - redis-data:/data/db

  testeredis:
    image: "redis:alpine"
    restart: unless-stopped
    container_name: testeredis
    ports:
      - 6379:6379
    networks:
      - backend
    volumes:
      - testeredis-data:/data/db

  testerabbitmq:
    image: rabbitmq:3-management
    container_name: testerabbitmq
    volumes:
      - testerabbitmq-data:/data/db
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq-data:/data/db
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    networks:
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "false"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  testeredis-data:
    driver: local
  testerabbitmq-data:
    driver: local
  rabbitmq-data:
    driver: local
  redis-data:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
